import { User, Role, ApprovalStatus, DeliveryRequest, DeliveryStatus, GatePass, GatePassStatus, Announcement, Conversation, Message, VehicleType } from './types';

// Mock coordinates centered around a fictional estate in Lagos, Nigeria (approx 6.52 N, 3.37 E)
export const USERS: User[] = [
  { id: 'admin1', name: 'Dr. Amina Yusuf', email: 'admin@estate.com', phone: '08012345678', address: 'Estate Management Office', role: Role.ADMIN, photoUrl: 'https://i.pravatar.cc/150?u=admin1', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, lat: 6.5244, lng: 3.3792 },
  
  // Residents
  { id: 'res1', name: 'Chinedu Okoro', email: 'chinedu@email.com', phone: '08023456789', address: 'Block 1, Apt 2A', role: Role.RESIDENT, photoUrl: 'https://i.pravatar.cc/150?u=res1', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, proofOfAddressUrl: '/path/to/rent.pdf', meansOfIdUrl: '/path/to/id.pdf', lat: 6.5250, lng: 3.3790 },
  { id: 'res2', name: 'Funke Adebayo', email: 'funke@email.com', phone: '08034567890', address: 'Block 5, Apt 4B', role: Role.RESIDENT, photoUrl: 'https://i.pravatar.cc/150?u=res2', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, proofOfAddressUrl: '/path/to/sales.pdf', meansOfIdUrl: '/path/to/id2.pdf', lat: 6.5235, lng: 3.3805 },
  { id: 'res3', name: 'Ngozi Eze', email: 'ngozi@email.com', phone: '08045678901', address: 'Block 2, Apt 1C', role: Role.RESIDENT, photoUrl: 'https://i.pravatar.cc/150?u=res3', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, proofOfAddressUrl: '/path/to/rent3.pdf', meansOfIdUrl: '/path/to/id3.pdf', lat: 6.5255, lng: 3.3795 },
  { id: 'res4', name: 'Tayo Johnson', email: 'tayo@email.com', phone: '08056789012', address: 'Block 8, Penthouse', role: Role.RESIDENT, photoUrl: 'https://i.pravatar.cc/150?u=res4', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, proofOfAddressUrl: '/path/to/rent4.pdf', meansOfIdUrl: '/path/to/id4.pdf', lat: 6.5228, lng: 3.3810 },
  { id: 'res5', name: 'Fatima Abubakar', email: 'fatima@email.com', phone: '08067890123', address: 'Block 3, Apt 3A', role: Role.RESIDENT, photoUrl: 'https://i.pravatar.cc/150?u=res5', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, proofOfAddressUrl: '/path/to/rent5.pdf', meansOfIdUrl: '/path/to/id5.pdf', lat: 6.5260, lng: 3.3788 },
  { id: 'res6', name: 'Dele Ojo', email: 'dele@email.com', phone: '08078901234', address: 'Block 10, Apt 5D', role: Role.RESIDENT, photoUrl: 'https://i.pravatar.cc/150?u=res6', approvalStatus: ApprovalStatus.PENDING, operatesOutsideEstate: false, proofOfAddressUrl: '/path/to/rent6.pdf', meansOfIdUrl: '/path/to/id6.pdf', lat: 6.5233, lng: 3.3799 },
  { id: 'res7', name: 'Bisi Williams', email: 'bisi@email.com', phone: '08089012345', address: 'Block 4, Apt 2B', role: Role.RESIDENT, photoUrl: 'https://i.pravatar.cc/150?u=res7', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, proofOfAddressUrl: '/path/to/rent7.pdf', meansOfIdUrl: '/path/to/id7.pdf', lat: 6.5245, lng: 3.3812 },

  // Riders
  { id: 'rider1', name: 'Musa Aliyu', email: 'musa@rider.com', phone: '08045678901', address: 'Rider Stand, Gate 1', role: Role.DISPATCH_RIDER, photoUrl: 'https://i.pravatar.cc/150?u=rider1', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, vehicleOwnershipUrl: '/path/to/vehicle.pdf', driverLicenceUrl: '/path/to/driver-licence.pdf', vehicleLicencePlate: 'ABC-123DE', vehicleType: VehicleType.MOTORCYCLE, lat: 6.5240, lng: 3.3785, isOnline: true, rating: 4.8, reviewCount: 125 },
  { id: 'rider2', name: 'David Jones', email: 'david@rider.com', phone: '08056789012', address: '123, Main Street', role: Role.DISPATCH_RIDER, photoUrl: 'https://i.pravatar.cc/150?u=rider2', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: true, vehicleOwnershipUrl: '/path/to/vehicle2.pdf', driverLicenceUrl: '/path/to/driver-licence2.pdf', vehicleLicencePlate: 'XYZ-789FG', vehicleType: VehicleType.TRICYCLE, lat: 6.5280, lng: 3.3850, isOnline: false, rating: 4.5, reviewCount: 88 },
  { id: 'rider3', name: 'Aisha Bello', email: 'aisha@rider.com', phone: '08089012345', address: 'Rider Stand, Gate 2', role: Role.DISPATCH_RIDER, photoUrl: 'https://i.pravatar.cc/150?u=rider3', approvalStatus: ApprovalStatus.SUSPENDED, operatesOutsideEstate: false, vehicleType: VehicleType.BICYCLE, vehicleLicencePlate: 'B-001', lat: 6.5275, lng: 3.3815, isOnline: true, rating: 4.2, reviewCount: 45 },
  { id: 'rider4', name: 'Tunde Bakare', email: 'tunde@rider.com', phone: '08090123456', address: 'Rider Stand, Gate 1', role: Role.DISPATCH_RIDER, photoUrl: 'https://i.pravatar.cc/150?u=rider4', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, vehicleOwnershipUrl: '/path/to/vehicle4.pdf', driverLicenceUrl: '/path/to/driver-licence4.pdf', vehicleLicencePlate: 'LAG-456JK', vehicleType: VehicleType.MOTORCYCLE, lat: 6.5242, lng: 3.3787, isOnline: true, rating: 4.9, reviewCount: 210 },
  { id: 'rider5', name: 'Sade Williams', email: 'sade@rider.com', phone: '08101234567', address: '25, External Road', role: Role.DISPATCH_RIDER, photoUrl: 'https://i.pravatar.cc/150?u=rider5', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: true, vehicleOwnershipUrl: '/path/to/vehicle5.pdf', driverLicenceUrl: '/path/to/driver-licence5.pdf', vehicleLicencePlate: 'OGN-789LM', vehicleType: VehicleType.CAR, lat: 6.5295, lng: 3.3860, isOnline: false, rating: 4.7, reviewCount: 95 },
  { id: 'rider6', name: 'Usman Danjuma', email: 'usman@rider.com', phone: '08112345678', address: 'Rider Stand, Gate 1', role: Role.DISPATCH_RIDER, photoUrl: 'https://i.pravatar.cc/150?u=rider6', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, vehicleType: VehicleType.MOTORCYCLE, vehicleLicencePlate: 'FST-111AB', lat: 6.5241, lng: 3.3786, isOnline: true, rating: 4.6, reviewCount: 78 },
  { id: 'rider7', name: 'Paul Ibe', email: 'paul@rider.com', phone: '08123456789', address: '50, Outer Ring Rd', role: Role.DISPATCH_RIDER, photoUrl: 'https://i.pravatar.cc/150?u=rider7', approvalStatus: ApprovalStatus.PENDING, operatesOutsideEstate: true, vehicleType: VehicleType.TRICYCLE, vehicleLicencePlate: 'APP-222BC', lat: 6.5310, lng: 3.3890, isOnline: false, rating: 5.0, reviewCount: 12 },
  { id: 'rider8', name: 'Kingsley Ugwu', email: 'kingsley@rider.com', phone: '08134567890', address: 'Rider Stand, Gate 2', role: Role.DISPATCH_RIDER, photoUrl: 'https://i.pravatar.cc/150?u=rider8', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, vehicleType: VehicleType.BICYCLE, vehicleLicencePlate: 'B-002', lat: 6.5276, lng: 3.3816, isOnline: true, rating: 4.3, reviewCount: 30 },
  { id: 'rider9', name: 'Samson Ade', email: 'samson@rider.com', phone: '08145678901', address: 'Rider Stand, Gate 1', role: Role.DISPATCH_RIDER, photoUrl: 'https://i.pravatar.cc/150?u=rider9', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, vehicleType: VehicleType.MOTORCYCLE, vehicleLicencePlate: 'KJA-333CD', lat: 6.5243, lng: 3.3788, isOnline: false, rating: 4.8, reviewCount: 150 },
  { id: 'rider10', name: 'Victor Eze', email: 'victor@rider.com', phone: '08156789012', address: '88, Expressway', role: Role.DISPATCH_RIDER, photoUrl: 'https://i.pravatar.cc/150?u=rider10', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: true, vehicleType: VehicleType.BUS, vehicleLicencePlate: 'GGE-444DE', lat: 6.5325, lng: 3.3910, isOnline: true, rating: 4.9, reviewCount: 180 },

  // Stores
  { id: 'store1', name: 'Chioma Nwosu', businessName: 'Mama Chi\'s Groceries', email: 'mama.chi@store.com', phone: '08067890123', address: 'Shop 3, Estate Plaza', role: Role.STORE, photoUrl: 'https://i.pravatar.cc/150?u=store1', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, storeOwnershipUrl: '/path/to/store-bill.pdf', hoursOfOperation: 'Mon - Sat: 8 AM - 9 PM', incorporationCertUrl: '/path/to/cac.pdf', meansOfIdUrl: '/path/to/chioma-id.pdf', lat: 6.5260, lng: 3.3800 },
  { id: 'store2', name: 'Bola Ahmed', businessName: 'Bola\'s Pharmacy', email: 'bola.pharma@store.com', phone: '08112345678', address: 'Shop 5, Estate Plaza', role: Role.STORE, photoUrl: 'https://i.pravatar.cc/150?u=store2', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, storeOwnershipUrl: '/path/to/store-bill2.pdf', hoursOfOperation: 'Mon - Sun: 9 AM - 10 PM', incorporationCertUrl: '/path/to/cac2.pdf', meansOfIdUrl: '/path/to/bola-id.pdf', lat: 6.5262, lng: 3.3803 },
  { id: 'store3', name: 'Emeka Oji', businessName: 'Emeka\'s Electronics', email: 'emeka.electro@store.com', phone: '08123456789', address: '10, Commercial Avenue', role: Role.STORE, photoUrl: 'https://i.pravatar.cc/150?u=store3', approvalStatus: ApprovalStatus.PENDING, operatesOutsideEstate: true, storeOwnershipUrl: '/path/to/store-bill3.pdf', hoursOfOperation: 'Mon - Fri: 9 AM - 6 PM', incorporationCertUrl: '/path/to/cac3.pdf', meansOfIdUrl: '/path/to/emeka-id.pdf', lat: 6.5300, lng: 3.3880 },
  { id: 'store4', name: 'Hassan Bello', businessName: 'Daily Needs Supermart', email: 'daily.needs@store.com', phone: '08167890123', address: 'Shop 1, Estate Plaza', role: Role.STORE, photoUrl: 'https://i.pravatar.cc/150?u=store4', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, hoursOfOperation: 'Mon - Sun: 7 AM - 10 PM', lat: 6.5258, lng: 3.3798 },
  { id: 'store5', name: 'Amina Salisu', businessName: 'Fresh Bakes Bakery', email: 'fresh.bakes@store.com', phone: '08178901234', address: 'Shop 8, Estate Plaza', role: Role.STORE, photoUrl: 'https://i.pravatar.cc/150?u=store5', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, hoursOfOperation: 'Tue - Sun: 6 AM - 7 PM', lat: 6.5265, lng: 3.3808 },
  { id: 'store6', name: 'Tope Alabi', businessName: 'The Tech Hub', email: 'tech.hub@store.com', phone: '08189012345', address: '22, Innovation Drive', role: Role.STORE, photoUrl: 'https://i.pravatar.cc/150?u=store6', approvalStatus: ApprovalStatus.PENDING, operatesOutsideEstate: true, hoursOfOperation: 'Mon - Sat: 10 AM - 8 PM', lat: 6.5330, lng: 3.3920 },
  { id: 'store7', name: 'Ify Okeke', businessName: 'Luxe Fashion Boutique', email: 'luxe.fashion@store.com', phone: '09012345678', address: 'Shop 12, Estate Plaza', role: Role.STORE, photoUrl: 'https://i.pravatar.cc/150?u=store7', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, hoursOfOperation: 'Mon - Sat: 10 AM - 9 PM', lat: 6.5268, lng: 3.3811 },
  { id: 'store8', name: 'Gbenga Peters', businessName: 'QuickFix Hardware', email: 'quick.fix@store.com', phone: '09023456789', address: '45, Industrial Layout', role: Role.STORE, photoUrl: 'https://i.pravatar.cc/150?u=store8', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: true, hoursOfOperation: 'Mon - Sat: 8 AM - 6 PM', lat: 6.5340, lng: 3.3940 },

  // Service Providers
  { id: 'sp1', name: 'Femi Adekunle (Plumber)', email: 'fixit@services.com', phone: '08078901234', address: '456, Market Road', role: Role.SERVICE_PROVIDER, photoUrl: 'https://i.pravatar.cc/150?u=sp1', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: true, hoursOfOperation: '24/7 Emergency Service', tradeLicenceUrl: '/path/to/trade-licence.pdf', meansOfIdUrl: '/path/to/femi-id.pdf', residenceProofUrl: '/path/to/femi-residence.pdf', lat: 6.5220, lng: 3.3770 },
  { id: 'sp2', name: 'Grace Eze (Cleaner)', email: 'grace.cleaners@services.com', phone: '08134567890', address: 'Suite 10, Service Complex', role: Role.SERVICE_PROVIDER, photoUrl: 'https://i.pravatar.cc/150?u=sp2', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, hoursOfOperation: 'By appointment', tradeLicenceUrl: '/path/to/trade-licence2.pdf', meansOfIdUrl: '/path/to/grace-id.pdf', residenceProofUrl: '/path/to/grace-residence.pdf', lat: 6.5255, lng: 3.3798 },
  { id: 'sp3', name: 'John Doe (Gardener)', email: 'johndoe.gardens@services.com', phone: '08145678901', address: 'Green Valley Estate', role: Role.SERVICE_PROVIDER, photoUrl: 'https://i.pravatar.cc/150?u=sp3', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: true, hoursOfOperation: 'Mon - Sat: 8 AM - 5 PM', tradeLicenceUrl: '/path/to/trade-licence3.pdf', meansOfIdUrl: '/path/to/john-id.pdf', residenceProofUrl: '/path/to/john-residence.pdf', lat: 6.5210, lng: 3.3760 },
  { id: 'sp4', name: 'Titi Coker (Tailor)', email: 'titi.stitches@services.com', phone: '09034567890', address: 'Shop 15, Fashion Wing', role: Role.SERVICE_PROVIDER, photoUrl: 'https://i.pravatar.cc/150?u=sp4', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, hoursOfOperation: 'Mon - Sat: 9 AM - 7 PM', lat: 6.5270, lng: 3.3814 },
  { id: 'sp5', name: 'Ahmed Bello (Electrician)', email: 'ahmed.sparks@services.com', phone: '09045678901', address: '77, Powerline Avenue', role: Role.SERVICE_PROVIDER, photoUrl: 'https://i.pravatar.cc/150?u=sp5', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: true, hoursOfOperation: '24/7 Emergency Service', lat: 6.5200, lng: 3.3750 },
  { id: 'sp6', name: 'Rose Okeke (Nanny)', email: 'rose.cares@services.com', phone: '09056789012', address: 'Block 7, Apt 1A', role: Role.SERVICE_PROVIDER, photoUrl: 'https://i.pravatar.cc/150?u=sp6', approvalStatus: ApprovalStatus.SUSPENDED, operatesOutsideEstate: false, hoursOfOperation: 'Live-in / By schedule', lat: 6.5238, lng: 3.3802 },
  { id: 'sp7', name: 'Mike Adenuga (Car Wash)', email: 'mike.wash@services.com', phone: '09067890123', address: 'Estate Car Wash Bay', role: Role.SERVICE_PROVIDER, photoUrl: 'https://i.pravatar.cc/150?u=sp7', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: false, hoursOfOperation: 'Mon - Sun: 8 AM - 6 PM', lat: 6.5248, lng: 3.3792 },
  { id: 'sp8', name: 'Daniel Olu (Tutor)', email: 'daniel.tutor@services.com', phone: '09078901234', address: '15, Knowledge Crescent', role: Role.SERVICE_PROVIDER, photoUrl: 'https://i.pravatar.cc/150?u=sp8', approvalStatus: ApprovalStatus.APPROVED, operatesOutsideEstate: true, hoursOfOperation: 'By appointment', lat: 6.5215, lng: 3.3765 },
];

export const DELIVERY_REQUESTS: DeliveryRequest[] = [
  { id: 'del1', requesterId: 'res1', requesterName: 'Chinedu Okoro', pickupAddress: 'Mama Chi\'s Groceries', dropoffAddress: 'Block 1, Apt 2A', description: 'Weekly grocery shopping', estimatedCost: 500, status: DeliveryStatus.COMPLETED, riderId: 'rider1', riderName: 'Musa Aliyu', createdAt: '2023-10-26T10:00:00Z', pickupLat: 6.5260, pickupLng: 3.3800 },
  { id: 'del2', requesterId: 'res2', requesterName: 'Funke Adebayo', pickupAddress: 'Gate 2', dropoffAddress: 'Block 5, Apt 4B', description: 'Pickup package from DHL', estimatedCost: 700, status: DeliveryStatus.IN_TRANSIT, riderId: 'rider2', riderName: 'David Jones', createdAt: '2023-10-27T11:30:00Z', pickupLat: 6.5275, pickupLng: 3.3815 },
  { id: 'del3', requesterId: 'res1', requesterName: 'Chinedu Okoro', pickupAddress: 'Laundry Hub', dropoffAddress: 'Block 1, Apt 2A', description: 'Collect dry cleaning', estimatedCost: 300, status: DeliveryStatus.PENDING, createdAt: '2023-10-27T14:00:00Z', pickupLat: 6.5248, pickupLng: 3.3795 },
  { id: 'del4', requesterId: 'res2', requesterName: 'Funke Adebayo', pickupAddress: 'Block 5, Apt 4B', dropoffAddress: 'Estate Post Office', description: 'Mail a letter', estimatedCost: 200, status: DeliveryStatus.PENDING, createdAt: '2023-10-28T09:00:00Z', pickupLat: 6.5235, pickupLng: 3.3805 },
  { id: 'del5', requesterId: 'res3', requesterName: 'Ngozi Eze', pickupAddress: 'Block 2, Apt 1C', dropoffAddress: '123, Main Street', description: 'Deliver package to external rider', status: DeliveryStatus.AWAITING_GATE_PASS, createdAt: '2023-10-29T10:00:00Z', pickupLat: 6.5255, pickupLng: 3.3795 },
];

export const GATE_PASSES: GatePass[] = [
  { id: 'gp1', residentId: 'res1', residentName: 'Chinedu Okoro', visitorName: 'Femi Adekunle (Plumber)', visitorType: Role.SERVICE_PROVIDER, purpose: 'Fix leaking kitchen sink', visitDateTime: '2023-10-28T10:00:00Z', status: GatePassStatus.PENDING, qrCode: 'pending' },
  { id: 'gp2', residentId: 'res2', residentName: 'Funke Adebayo', visitorName: 'Jumia Delivery', visitorType: Role.DISPATCH_RIDER, purpose: 'Deliver online order', visitDateTime: '2023-10-27T15:00:00Z', status: GatePassStatus.APPROVED, qrCode: 'QR_CODE_XYZ789' },
  { id: 'gp3', residentId: 'res1', residentName: 'Chinedu Okoro', visitorName: 'Family Visit', visitorType: Role.RESIDENT, purpose: 'Visiting family', visitDateTime: '2023-10-26T18:00:00Z', status: GatePassStatus.USED, qrCode: 'QR_CODE_ABC123' },
  { id: 'gp4', residentId: 'res3', residentName: 'Ngozi Eze', visitorName: 'David Jones', visitorType: Role.DISPATCH_RIDER, purpose: 'Delivery Pickup for job #del5', visitDateTime: new Date().toISOString(), status: GatePassStatus.PENDING, qrCode: 'pending', targetVisitorId: 'rider2', linkedDeliveryId: 'del5' },
];

export const ANNOUNCEMENTS: Announcement[] = [
    { id: 'ann1', title: 'Security Update', content: 'Please be informed that the main gate will be closed for maintenance from 10 PM to 5 AM on Friday.', createdAt: '2023-10-25T08:00:00Z' },
    { id: 'ann2', title: 'Community Meeting', content: 'There will be a general residents meeting on Sunday at the community hall at 4 PM. Your attendance is crucial.', createdAt: '2023-10-26T12:00:00Z' },
];

export const CONVERSATIONS: Conversation[] = [
    { id: 'conv1', participantIds: ['res1', 'store1'], lastMessage: { text: 'Do you have fresh tomatoes?', timestamp: '2023-10-28T09:05:00Z' } },
    { id: 'conv2', participantIds: ['res2', 'rider2'], lastMessage: { text: 'I am at the gate now.', timestamp: '2023-10-27T11:32:00Z' } },
    { id: 'conv3', participantIds: ['res1', 'rider1'], lastMessage: { text: 'Thanks for the delivery!', timestamp: '2023-10-26T10:15:00Z' } },
];

export const MESSAGES: Message[] = [
    // Conversation 1: Chinedu & Mama Chi's Groceries
    { id: 'msg1', conversationId: 'conv1', senderId: 'res1', receiverId: 'store1', text: 'Good morning, do you have fresh tomatoes?', timestamp: '2023-10-28T09:05:00Z', read: true },
    { id: 'msg2', conversationId: 'conv1', senderId: 'store1', receiverId: 'res1', text: 'Yes we do, plenty of them!', timestamp: '2023-10-28T09:06:00Z', read: true },
    { id: 'msg3', conversationId: 'conv1', senderId: 'res1', receiverId: 'store1', text: 'Great, I will send a rider to pick some up.', timestamp: '2023-10-28T09:07:00Z', read: false },
    
    // Conversation 2: Funke & David Jones
    { id: 'msg4', conversationId: 'conv2', senderId: 'res2', receiverId: 'rider2', text: 'Hi David, are you close?', timestamp: '2023-10-27T11:30:00Z', read: true },
    { id: 'msg5', conversationId: 'conv2', senderId: 'rider2', receiverId: 'res2', text: 'Yes, almost at the estate gate.', timestamp: '2023-10-27T11:31:00Z', read: true },
    { id: 'msg6', conversationId: 'conv2', senderId: 'rider2', receiverId: 'res2', text: 'I am at the gate now.', timestamp: '2023-10-27T11:32:00Z', read: false },
    
    // Conversation 3: Chinedu & Musa Aliyu
    { id: 'msg7', conversationId: 'conv3', senderId: 'res1', receiverId: 'rider1', text: 'Thanks for the delivery!', timestamp: '2023-10-26T10:15:00Z', read: true },
    { id: 'msg8', conversationId: 'conv3', senderId: 'rider1', receiverId: 'res1', text: 'You are welcome!', timestamp: '2023-10-26T10:16:00Z', read: true },
];